logging:
  level:
    root: warn

spring:

  datasource:
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}

  jpa:
    show-sql: false

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

api:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    region: ${S3_REGION:us-west-2}
    url: ${S3_URL}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
