version: "3"

services:

  sonarqube:
    image: sonarqube:community
    volumes:
      - sonarqube-data-volume:/opt/sonarqube/data
      - sonarqube-extensions-volume:/opt/sonarqube/extensions
      - sonarqube-logs-volume:/opt/sonarqube/logs
    ports:
      - "9010:9000"
volumes:
  sonarqube-data-volume:
  sonarqube-extensions-volume:
  sonarqube-logs-volume:
