apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-api-configmap
  namespace: todo-app-api
  labels:
    app: todo-app-api
data:
  {{- range $key, $value := .Values.configmapData }}
    {{ $key }}: {{ $value }}
  {{- end }}
