apiVersion: v1
kind: Secret
metadata:
  name: todo-app-api-secret
  namespace: todo-app-api
  labels:
    app: todo-app-api
type: Opaque
data:
  {{- range $key, $value := .Values.secretData }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
