apiVersion: v1
kind: Service
metadata:
  name: todo-app-api-service
  namespace: todo-app-api
  labels:
    app: todo-app-api
spec:
  selector:
    app: todo-app-api
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
