apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-web-configmap
  namespace: todo-app-web
  labels:
    app: todo-app-web
data:
  {{- range $key, $value := .Values.configmapData }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
