spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/${FIREBASE_PROJECT_ID:copeo-dev}
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com

server:
  port: 8080
  servlet:
    context-path: /api
    multipart:
      max-file-size: 700KB
      max-request-size: 700KB
      resolve-lazily: true

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

api:
  build:
    timestamp: @timestamp@
  versions:
    api-version: @project.version@
  page:
    size: 10
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS,HEAD}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
