logging:
  level:
    com.fabbo: trace
    org.springframework.security: info
    org.springframework.transaction: trace

spring:
  config:
    import: optional:file:api.env.dev[.properties]

  datasource:
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: method

api:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    region: ${S3_REGION:us-west-2}
    url: ${S3_URL}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
