logging:
  level:
    com.fabbo: trace
    org.springframework.security: info
    org.springframework.transaction: trace

spring:
  config:
    import: optional:file:api.env.dev[.properties]

  datasource:
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

api:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS,HEAD}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
