logging:
  level:
    root: warn

spring:

  datasource:
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}

  jpa:
    show-sql: false

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

api:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    region: ${S3_REGION:us-west-2}
    url: ${S3_URL}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS,HEAD}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
