name: React WEB Build, Test and Upload to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'web-react/**'

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.18

      - name: Install dependencies
        run: npm install
        working-directory: ./web-react

      - name: Build
        run: npm run build
        working-directory: ./web-react

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          export APP_VERSION=$(node -p "require('./package.json').version")
          echo "Using version ${APP_VERSION}"
          
          IMAGE_TAG="${DOCKER_REPO_NAME}:${APP_VERSION}-react"
          LATEST_TAG="${DOCKER_REPO_NAME}:latest"
          
          docker build . -t ${IMAGE_TAG}
          docker tag ${IMAGE_TAG} ${LATEST_TAG}
          
          docker push ${IMAGE_TAG}
          docker push ${LATEST_TAG}
        working-directory: ./web-react
        env:
          DOCKER_REPO_NAME: ${{ secrets.DOCKER_WEB_REPO_NAME }}
